import { Article, NewsPost, Category } from './types'

export const mockCategories: Category[] = [
  { id: '1', name_en: 'Early History', name_ta: 'ஆரம்பகால வரலாறு', slug: 'early-history', icon: '📜', article_count: 42, parent_id: null },
  { id: '2', name_en: 'Mosques & Places', name_ta: 'மசூதிகள் & இடங்கள்', slug: 'mosques-places', icon: '🕌', article_count: 31, parent_id: null },
  { id: '3', name_en: 'Culture & Traditions', name_ta: 'கலாச்சாரம் & மரபுகள்', slug: 'culture-traditions', icon: '🎨', article_count: 27, parent_id: null },
  { id: '4', name_en: 'Notable Figures', name_ta: 'சிறப்பு ஆளுமைகள்', slug: 'notable-figures', icon: '👑', article_count: 18, parent_id: null },
  { id: '5', name_en: 'Literature & Arts', name_ta: 'இலக்கியம் & கலை', slug: 'literature-arts', icon: '📖', article_count: 22, parent_id: null },
  { id: '6', name_en: 'Community & Society', name_ta: 'சமூகம் & கல்வி', slug: 'community-society', icon: '🤝', article_count: 35, parent_id: null },
]

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'அரபு வணிகர்கள்: இலங்கையில் இஸ்லாத்தின் தோற்றம்',
    slug: 'arab-traders-origins-of-islam-in-sri-lanka',
    content: `அரபு வணிகர்களின் வருகை

கி.பி. 7 ஆம் நூற்றாண்டில், இஸ்லாத்தின் தோற்றத்திற்கு சற்று முன்னரே, அரபு வணிகர்கள் இந்திய மகாசமுத்திரம் வழியாக இலங்கையுடன் வர்த்தக தொடர்புகளை மேற்கொண்டிருந்தனர்.`,
    category: 'Early History',
    category_slug: 'early-history',
    author: 'டாக்டர் A. முஹம்மட்',
    featured_image: '',
    views: 8240,
    is_featured: true,
    author_id: null,
    author_link: '',
    gallery: [],
    categories: [],
    published_at: '2026-03-10T00:00:00Z',
  },
  {
    id: '2',
    title: 'கெச்சிமலை மசூதி: 1,000 ஆண்டு வரலாறு',
    slug: 'kechimalai-mosque-1000-year-history',
    content: '',
    category: 'Mosques & Places',
    category_slug: 'mosques-places',
    author: 'Z. அபூபக்கர்',
    featured_image: '',
    views: 5610,
    is_featured: true,
    author_id: null,
    author_link: '',
    gallery: [],
    categories: [],
    published_at: '2026-03-05T00:00:00Z',
  },
  {
    id: '3',
    title: 'கண்டியன் இராச்சியத்தில் முஸ்லிம் வணிகர்கள்',
    slug: 'muslim-traders-kandyan-kingdom',
    content: '',
    category: 'Early History',
    category_slug: 'early-history',
    author: 'M. ஃபசீல்',
    featured_image: '',
    views: 4120,
    is_featured: true,
    author_id: null,
    author_link: '',
    gallery: [],
    categories: [],
    published_at: '2026-02-28T00:00:00Z',
  },
  {
    id: '4',
    title: 'சூஃபி மரபுகள் மற்றும் தர்காக்கள்',
    slug: 'sufi-traditions-dargahs-sri-lanka',
    content: '',
    category: 'Culture & Traditions',
    category_slug: 'culture-traditions',
    author: 'I. ஹமீட்',
    featured_image: '',
    views: 3820,
    is_featured: false,
    author_id: null,
    author_link: '',
    gallery: [],
    categories: [],
    published_at: '2026-02-20T00:00:00Z',
  },
  {
    id: '5',
    title: 'இலங்கை முஸ்லிம் உணவு பாரம்பரியம்',
    slug: 'sri-lanka-muslim-food-heritage',
    content: '',
    category: 'Culture & Traditions',
    category_slug: 'culture-traditions',
    author: 'F. அமீனா',
    featured_image: '',
    views: 2940,
    is_featured: false,
    author_id: null,
    author_link: '',
    gallery: [],
    categories: [],
    published_at: '2026-02-15T00:00:00Z',
  },
  {
    id: '6',
    title: 'சர் ரசீக் ஃபரீட்: இலங்கை முஸ்லிம் தலைமை',
    slug: 'sir-razik-fareed-sri-lanka-muslim-leadership',
    content: '',
    category: 'Notable Figures',
    category_slug: 'notable-figures',
    author: 'டாக்டர் A. முஹம்மட்',
    featured_image: '',
    views: 6730,
    is_featured: false,
    author_id: null,
    author_link: '',
    gallery: [],
    categories: [],
    published_at: '2026-02-10T00:00:00Z',
  },
]

export const mockNews: NewsPost[] = [
  {
    id: '1',
    title: 'கொழும்பில் ரமழான் பாரம்பரிய கண்காட்சி திறப்பு',
    slug: 'ramadan-heritage-exhibition-colombo',
    content: `கண்காட்சியின் சிறப்பு\n\nகொழும்பு தேசிய அருங்காட்சியகத்தில் நடைபெறும் இந்த சிறப்பு கண்காட்சி, இலங்கை முஸ்லிம்களின் 1,400 ஆண்டு கால வரலாற்றை படங்கள், ஆவணங்கள் மற்றும் அரிய கலைப்பொருட்கள் மூலம் விளக்குகிறது.`,
    featured_image: '',
    news_type: 'special',
    published_at: '2026-03-20T00:00:00Z',
  },
  {
    id: '2',
    title: '14 ஆம் நூற்றாண்டு கையெழுத்து நூல்கள் தேசிய காப்பகத்திற்கு',
    slug: '14th-century-manuscripts-national-archives',
    content: '',
    featured_image: '',
    news_type: 'special',
    published_at: '2026-03-18T00:00:00Z',
  },
  {
    id: '3',
    title: 'பேருவளை மசூதி புனரமைப்புக்கு அரசாங்க நிதி அனுமதி',
    slug: 'beruwala-mosque-restoration-government-funding',
    content: '',
    featured_image: '',
    news_type: 'special',
    published_at: '2026-03-15T00:00:00Z',
  },
  {
    id: '4',
    title: 'இலங்கை முஸ்லிம் இளைஞர் வரலாற்று மாநாடு',
    slug: 'sri-lanka-muslim-youth-history-conference',
    content: '',
    featured_image: '',
    news_type: 'janaza',
    published_at: '2026-03-12T00:00:00Z',
  },
  {
    id: '5',
    title: 'கண்டியில் புதிய இஸ்லாமிய ஆய்வு மையம் திறப்பு',
    slug: 'new-islamic-research-centre-kandy',
    content: '',
    featured_image: '',
    news_type: 'janaza',
    published_at: '2026-03-08T00:00:00Z',
  },
  {
    id: '6',
    title: 'இலங்கை முஸ்லிம் வரலாற்று புத்தகம் — புதிய பதிப்பு வெளியீடு',
    slug: 'sri-lanka-muslim-history-book-new-edition',
    content: '',
    featured_image: '',
    news_type: 'janaza',
    published_at: '2026-03-05T00:00:00Z',
  },
  {
    id: '7',
    title: 'கல்முனை பழைய மசூதி — யுனெஸ்கோ பாரம்பரிய தளமாக பரிந்துரை',
    slug: 'kalmunai-old-mosque-unesco-heritage-nomination',
    content: '',
    featured_image: '',
    news_type: 'special',
    published_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '8',
    title: 'முஸ்லிம் பெண்களின் வரலாற்றுப் பங்களிப்பு — புதிய ஆவணப்படம்',
    slug: 'muslim-women-historical-contributions-documentary',
    content: '',
    featured_image: '',
    news_type: 'janaza',
    published_at: '2026-02-25T00:00:00Z',
  },
]
